### ISSUE TITLE
Received write error of 5 on DB1,INT1118

### ISSUE THREAD

**Issue by MrDev2020** [Ivanrodpar/nodes7comm#3]
I can read this address but i cannot write to this address  

(node:21984) UnhandledPromiseRejectionWarning: Error: Received write error of 5 on DB1,INT1118
    at Desktop\ysplitLOGO\node_modules\nodes7comm\lib\nodes7comm.js:2289:39
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by Ivanrodpar** [comment]
1- What value are you trying to write?

2- Are you making concurrent read or write request on the moment that gives that error? 

3- What happen when you make a test whit the code below
     await s7comm.writeItems(['DB1,INT1118'], [1]);

**Comment by MrDev2020** [comment]
Hi I found the solution. But can you give me example how to use a callback in the connection? i would like to identify and write an output when the connection has failed or disconnected. Hope you can give simple example. Thank you in advance.
